### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-create#10]
I think we can release this initial version.

**Comment by jeddy3** [comment]
I believe we're ready for `0.1.0` release.

**Comment by ybiquitous** [comment]
Agree 👍🏼

**Comment by jeddy3** [comment]
Should have time tomorrow, unless anyone beats me to it.

**Comment by mattxwang** [comment]
Exciting!

> @mattxwang What's your npm username so I can add you to the package?

Didn't have one before, so just made an account; [mattxwang](https://www.npmjs.com/~mattxwang).

**Comment by jeddy3** [comment]
@mattxwang Invited,
@ybiquitous You should now have access via the stylelint developer npm group.

We should do a bit more testing ourselves, then open a PR to update the Stylelint getting started guide to use this package.

**Comment by ybiquitous** [comment]
@jeddy3 Thanks. I can now have access to invite maintainers on npmjs.com. 👍🏼 

BTW, Hasn't [`stylelint-create`](https://www.npmjs.com/package/create-stylelint) been published on npm yet?

**Comment by jeddy3** [comment]
> BTW, Hasn't [stylelint-create](https://www.npmjs.com/package/create-stylelint) been published on npm yet?

We got the package name wrong 😅. It should be `create-stylelint` rather than `stylelint-create`. 

I've:

- deleted `stylelint-create` from the registry
- rename this repo
- renamed the package (in the `package.json` and the README)
- published the `create-stylelint` package as `0.1.1`

`npm init stylelint` now works for me.

If it works for both of you too, I think we can open a PR is Stylelint to update the docs.

@mattxwang You should have received a new invite to the npm package.
@ybiquitous You should see the new package under the Stylelint npm organisation.

**Comment by ybiquitous** [comment]
Great! Very useful! 🎉
